defaults:
  run:
    shell: bash
    working-directory: yudao-ui-admin
env:
  TZ: Asia/Shanghai
  WORK_DIR: yudao-ui-admin
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.15.1
    - continue-on-error: true
      name: Set node version to ${{ matrix.node_version }}
      uses: actions/setup-node@v2
      with:
        cache: yarn
        cache-dependency-path: yudao-ui-admin/yarn.lock
        node-version: ${{ matrix.node_version }}
    - continue-on-error: true
      name: Install deps
      run: node --version && yarn --version && yarn install
    - continue-on-error: true
      name: Build
      run: yarn build:prod
    strategy:
      matrix:
        node_version:
        - 14.x
        - 16.x
name: yudao-ui-admin CI
on:
  repository_dispatch:
    types: trigger-ga___yudao-ui-admin.yml
